## Fremont Bridge Cycling Dashboard
### Visualisation Techniques 
**Author:** Arkadiusz Jedrzejewski 
**Date:** June 2026

In [5]:
# Install required packages
import sys
!{sys.executable} -m pip install dash plotly # APPENDING THIS LINE TO INSTALL DASH AND PLOTLY

# Create a Dash application
from dash import Dash, dcc, html, Input, Output
import pandas as pd
import numpy as np
import plotly.express as px

Requirement already satisfied: dash in /opt/anaconda3/lib/python3.13/site-packages (4.2.0)
Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.13/site-packages (6.3.0)
Requirement already satisfied: Flask<3.2,>=1.0.4 in /opt/anaconda3/lib/python3.13/site-packages (from dash) (3.1.2)
Requirement already satisfied: Werkzeug<3.2 in /opt/anaconda3/lib/python3.13/site-packages (from dash) (3.1.3)
Requirement already satisfied: importlib-metadata in /opt/anaconda3/lib/python3.13/site-packages (from dash) (8.7.0)
Requirement already satisfied: typing_extensions>=4.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from dash) (4.15.0)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (from dash) (2.32.5)
Requirement already satisfied: retrying in /opt/anaconda3/lib/python3.13/site-packages (from dash) (1.4.2)
Requirement already satisfied: nest-asyncio in /opt/anaconda3/lib/python3.13/site-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.13/site-packages (from dash) (80.9.0)
Requirement already satisfied: janus>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from dash) (2.0.0)
Requirement already satisfied: blinker>=1.9.0 in /opt/anaconda3/lib/python3.13/site-packages (from Flask<3.2,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /opt/anaconda3/lib/python3.13/site-packages (from Flask<3.2,>=1.0.4->dash) (8.2.1)
Requirement already satisfied: itsdangerous>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from Flask<3.2,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /opt/anaconda3/lib/python3.13/site-packages (from Flask<3.2,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from Flask<3.2,>=1.0.4->dash) (3.0.2)
Requirement already satisfied: narwhals>=1.15.1 in /opt/anaconda3/lib/python3.13/site-packages (from plotly) (2.7.0)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.13/site-packages (from plotly) (25.0)
Requirement already satisfied: zipp>=3.20 in /opt/anaconda3/lib/python3.13/site-packages (from importlib-metadata->dash) (3.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests->dash) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests->dash) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests->dash) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests->dash) (2026.1.4)

In [6]:
# Load the dataset
df = pd.read_csv('../DATASETS/Fremont_Bridge_-_Combined_Bicycle_and_Scooter_Counter_20260615.csv')

In [7]:
# Display the first 5 rows of the dataset
df.head(5)

,Date,"Fremont Bridge Sidewalks, south of N 34th St Total","Fremont Bridge Sidewalks, south of N 34th St Cyclist West Sidewalk","Fremont Bridge Sidewalks, south of N 34th St Cyclist East Sidewalk"
0,05/31/2026 11:00:00 PM,33,9.0,24.0
1,05/31/2026 10:00:00 PM,51,20.0,31.0
2,05/31/2026 09:00:00 PM,64,30.0,34.0
3,05/31/2026 08:00:00 PM,148,72.0,76.0
4,05/31/2026 07:00:00 PM,184,85.0,99.0

In [8]:
# Rename columns for easier access
df.columns = ['Date', 'Total', 'West_Sidewalk', 'East_Sidewalk']
df.head(5)

                     Date Total  West_Sidewalk  East_Sidewalk
0  05/31/2026 11:00:00 PM    33            9.0           24.0
1  05/31/2026 10:00:00 PM    51           20.0           31.0
2  05/31/2026 09:00:00 PM    64           30.0           34.0
3  05/31/2026 08:00:00 PM   148           72.0           76.0
4  05/31/2026 07:00:00 PM   184           85.0           99.0

In [10]:
# Basic dataset information
df.shape
df.info()
df.describe() 
df.isnull().sum()  # Check for missing values  
df['Date'] = pd.to_datetime(df['Date'])  # APPENDIX: convert 'Date' column to datetime format

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119747 entries, 0 to 119746
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           119747 non-null  object
 1   Total          119717 non-null  object
 2   West_Sidewalk  119717 non-null  float64
 3   East_Sidewalk  119717 non-null  float64
dtypes: float64(2), object(2)
memory usage: 3.7+ MB

/var/folders/v9/4323x23938z4qsywdlblqc740000gn/T/ipykernel_33356/134106843.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'])  # APPENDIX: convert 'Date' column to datetime format

AttributeError: module 'multiprocessing.reduction' has no attribute 'duplicate'